# **/.classpath
# **/.dockerignore
# **/.env
# **/.git
# **/.gitignore
# **/.project
# **/.settings
# **/.toolstarget
# **/.vs
# **/.vscode
# **/azds.yaml
# **/bin
# **/charts
# **/docker-compose*
# **/Dockerfile*
# **/node_modules
# **/npm-debug.log
**/obj
**/bin
# **/secrets.dev.yaml
# **/values.dev.yaml
# README.md