version: "3.2"
networks:
  reshop:

services:
  frontendapp:
    build:
      context: ./../../client
      dockerfile: ./../deployment/dev/Dockerfile.dev.frontend
    volumes:
      - ./../../client:/app
    networks:
      - reshop
    ports:
      - "3000:3000"
    stdin_open: true # docker run -i
    tty: true # docker run -t

  backendapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - DOTNET_ENVIRONMENT=development
    container_name: backend
    build:
      context: ./../../backend
      dockerfile: ../deployment/dev/Dockerfile.dev.backend
    volumes:
      - ./../../backend:/app
      - /app/API/bin/
      - /app/API/obj/
    networks:
      - reshop
    ports:
      - "5000:5000"
    stdin_open: true # docker run -i
    tty: true # docker run -t

  reshopdb:
    image: mysql
    container_name: reshopdb
    networks:
      - reshop
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./../database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql
    environment:
      MYSQL_ROOT_PASSWORD: example
