FROM mcr.microsoft.com/dotnet/sdk:5.0
ENV ASPNETCORE_ENVIRONMENT=development
ENV DOTNET_ENVIRONMENT=development

#install debugger for NET Core
RUN apt-get update
RUN apt-get install -y unzip
RUN curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l ~/vsdbg

#install dotnet-ef to make migrations
RUN dotnet tool install --global dotnet-ef --version 5.0
ENV PATH $PATH:/root/.dotnet/tools
WORKDIR /app

ENV USER=gruma
ENV UID=1000
ENV GID=1000
# default password for user
ENV PW=gruma
RUN useradd -m ${USER} --uid=${UID} && echo "${USER}:${PW}" | chpasswd
USER ${UID}:${GID}

# Copy csproj and restore as distinct layers
COPY --chown=gruma backend/backend.sln /app/backend/

COPY --chown=gruma backend/API /app/backend/API
COPY --chown=gruma backend/Application /app/backend/Application
COPY --chown=gruma backend/Domain /app/backend/Domain
COPY --chown=gruma backend/Persistence /app/backend/Persistence
COPY --chown=gruma data /app/data

RUN mkdir /app/backend/API/bin /app/backend/API/obj \
    /app/backend/Application/bin /app/backend/Application/obj \
    /app/backend/Domain/bin /app/backend/Domain/obj \
    /app/backend/Persistence/bin /app/backend/Persistence/obj

RUN chown -R gruma:gruma /app/backend/API/bin /app/backend/API/obj \
    /app/backend/Application/bin /app/backend/Application/obj \
    /app/backend/Domain/bin /app/backend/Domain/obj \
    /app/backend/Persistence/bin /app/backend/Persistence/obj

WORKDIR /app/backend/API
RUN dotnet restore

USER root
# ENTRYPOINT ["dotnet", "watch", "run", "environment=development"]