// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220109155034_categories")]
    partial class categories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Domain.Entities.Badge", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Productid")
                        .HasColumnType("char(36)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("Productid");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("parentid")
                        .HasColumnType("char(36)");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Domain.Entities.FilterAttribute", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("Domain.Entities.Image", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("Productid")
                        .HasColumnType("char(36)");

                    b.Property<bool>("isMain")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("Productid");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("brand")
                        .HasColumnType("longtext");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("price")
                        .HasColumnType("bigint");

                    b.Property<int>("qunatityInStock")
                        .HasColumnType("int");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("name");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Domain.Entities.Product_FilterAttribute", b =>
                {
                    b.Property<Guid>("FilterAttributeid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Productid")
                        .HasColumnType("char(36)");

                    b.HasKey("FilterAttributeid", "Productid");

                    b.HasIndex("Productid");

                    b.ToTable("Product_FilterAttribute");
                });

            modelBuilder.Entity("Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Productid")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<string>("text")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("Productid");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Domain.Entities.Badge", b =>
                {
                    b.HasOne("Domain.Entities.Product", null)
                        .WithMany("badges")
                        .HasForeignKey("Productid");
                });

            modelBuilder.Entity("Domain.Entities.Image", b =>
                {
                    b.HasOne("Domain.Entities.Product", null)
                        .WithMany("images")
                        .HasForeignKey("Productid");
                });

            modelBuilder.Entity("Domain.Entities.Product_FilterAttribute", b =>
                {
                    b.HasOne("Domain.Entities.FilterAttribute", "FilterAttribute")
                        .WithMany("product_FilterAttribute")
                        .HasForeignKey("FilterAttributeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("product_FilterAttribute")
                        .HasForeignKey("Productid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilterAttribute");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Review", b =>
                {
                    b.HasOne("Domain.Entities.Product", null)
                        .WithMany("reviews")
                        .HasForeignKey("Productid");
                });

            modelBuilder.Entity("Domain.Entities.FilterAttribute", b =>
                {
                    b.Navigation("product_FilterAttribute");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("badges");

                    b.Navigation("images");

                    b.Navigation("product_FilterAttribute");

                    b.Navigation("reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
